routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'admin','namespace'=>'Admin'], function() {
    Route::get('/',"HomeController@index");
    Route::resource('user', 'UserController');
    //Route::get('user',"UserController@index");
});

/*
Route::group(['middleware'=>'api','prefix' => 'api','namespace'=>'Api'], function() {
    Route::get('user', 'UserController@index');
});*/


Route::get('/{any}', 'SinglePageController@index')->where('any', '.*');

app/User.php
<?php

namespace App;
use Tymon\JWTAuth\Contracts\JWTSubject;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable implements JWTSubject    # 这里别忘了加
{
    use Notifiable;

    /**
     * Get the identifier that will be stored in the subject claim of the JWT.
     *
     * @return mixed
     */
    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    /**
     * Return a key value array, containing any custom claims to be added to the JWT.
     *
     * @return array
     */
    public function getJWTCustomClaims()
    {
        return [];
    }
}

app/Users.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Users extends Authenticatable
{
    use Notifiable;


    /**
     * The attributes that are mass assignable.
     * Users::create(['name' => 'Test','email' => 17623239881,'password' => bcrypt('123456')]);
     * @var array
     */
    protected $fillable = [
        'name', 'password','email','avatarUrl'
    ];

}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use App\AdminUser;

class UserController extends BaseController
{
    public function index()
    {
        $users = DB::select('select * from admin_users');

        return view('admin.user.index', ['users' => $users]);

    }


    public function create()
    {


        return view('admin.user.add');
    }


    public function edit($id)
    {

        $user = DB::table('admin_users')->where('id', $id)->first();
        //$user = DB::select('select * from admin_users where id = ?', [$id]);
        //print_r($user);
        return view('admin.user.add', ['user' => $user]);

    }


    public function store(Request $request)
    {

        $request->validate([
            'username'=>'required',
            'name'=>'required',
            'password'=> 'required|integer',
        ]);
        $share = new AdminUser([
            'username' => $request->get('username'),
            'name' => $request->get('name'),
            'password'=> $request->get('password'),
        ]);
        $result = $share->save();

        if ($result) {

            return $this->ajax_msg('操作成功','/admin/user');
        }

        return $this->ajax_msg('操作失败','/admin/user',0);
    }


    public function update(Request $request,$id)
    {

        $request->validate([
            'username'=>'required',
            'name'=>'required',
            'password'=> 'required|integer',
        ]);

        $share = AdminUser::find($id);
        $share->username = $request->get('username');
        $share->name = $request->get('name');
        $share->password = $request->get('password');
       $result =  $share->save();
        if ($result) {

            return $this->ajax_msg('操作成功','/admin/user');
        }

        return $this->ajax_msg('操作失败','/admin/user',0);
    }
    
}

app/Http/Controllers/Api/UserController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\AdminUser;

class UserController extends Controller
{
    public function index(){

        $users = DB::select('select * from admin_users');

        return response()->json($users);

    }

    public function show($id){

        $user = AdminUser::find($id);
        //$user = DB::select('select * from admin_users where id = ?', [$id]);
        //print_r($user);
        return response()->json($user);

    }
}

app/Http/Controllers/UsersController.php
<?php

// PostController.php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Users;

class UsersController extends Controller
{

    public function index(Request $request)
    {
        $post = new Users([
            'username' => $request->post('username'),
            'password' => encrypt($request->post('password'))
        ]);

        $result = $post->find($post);

        if($result){
            $data = [
                'token' => '123456'
            ];
            return $this->vue_msg($data,'success');

        }else{
            return $this->vue_msg('操作失败','error');

        }

    }

    public function store(Request $request)
    {
        $post = new Users([
            'name' => $request->post('name'),
            'avatarUrl' => $request->post('avatarUrl'),
            'password' => bcrypt('55555'),
            'email' => '12@qq.com'
        ]);

        $post->save();

        return $this->vue_msg('操作成功','success');
    }

    public function token(){

    }

}

resources/views/admin/user/add.blade.php
@extends('admin.public.base')

@section('content')


       <div class="row">
              <!-- left column -->
              <div class="col-md-12">
                <!-- general form elements -->
                <div class="box box-primary">
                  <div class="box-header with-border">
                    <h3 class="box-title">Quick Example</h3>
                  </div>
                  <!-- /.box-header -->
                  <!-- form start -->
                    @if(isset($user) && $user->id)
                     <form method="post" action="{{ route('user.update',$user->id) }}" class="horizontal">
                      @method('PATCH')
                      @csrf
                    @else
                    <form method="post" action="{{ route('user.store') }}" class="horizontal">
                    @csrf
                    @endif


                    <div class="box-body">

                      <div class="form-group">
                        <label for="exampleInputEmail1">Email address</label>
                        <input type="text" class="form-control" name="username" value="{{ $user->username ?? '' }}" id="exampleInputEmail1" placeholder="Enter email">
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Email address</label>
                        <input type="text" class="form-control" name="name" value="{{ $user->name ?? '' }}" id="exampleInputEmail1" placeholder="Enter email">
                      </div>
                      <div class="form-group">
                        <label for="exampleInputPassword1">Password</label>
                        <input type="password" class="form-control"  name="password" id="exampleInputPassword1" placeholder="Password">
                      </div>
                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                    <input type="button" value="提交" class="ajax-post btn btn-primary">
                    </div>
                  </form>

                </div>

@endsection


@section('script')

<script>


  $(function () {
    //Initialize Select2 Elements
    $('.select2').select2()

    //Date range picker
    $('#reservation').daterangepicker()
    CKEDITOR.replace('editor1')

  })
</script>
@endsection

resources/views/admin/user/index.blade.php
@extends('admin.public.base')

@section('content')

<div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Hover Data Table</h3>
              <h3 class="box-title"><a href="{{ URL::to('admin/user/create') }}">添加数据</a></h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example2" class="table table-bordered table-hover">
                <thead>
                <tr>
                  <th>Rendering engine</th>
                  <th>Browser</th>
                  <th>Platform(s)</th>
                  <th>Engine version</th>
                </tr>

                </thead>
                <tbody>
                @foreach($users as $val)
                    <tr>
                      <td>{{ $val->username }}</td>
                      <td>{{ $val->name }}</td>
                      <td>{{ $val->created_at }}</td>
                      <td><a href="{{ Route('user.edit',$val->id)}}">编辑</a></td>

                    </tr>
                @endforeach
                </tfoot>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->

@endsection


@section('script')

<script>


  $(function () {
    //Initialize Select2 Elements
    $('.select2').select2()

    //Date range picker
    $('#reservation').daterangepicker()
    CKEDITOR.replace('editor1')

  })
</script>
@endsection